
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME NUM TYPE VARNAME VARNUMnum  : NUM TYPE NAME VARNAME \n            |  NUM TYPE NAME\n            | NUM TYPE NAME VARNUMnum  : NUM NAME VARNAME \n            |  NUM NAME\n            | NUM NAME VARNUM'
    
_lr_action_items = {'NUM':([0,],[2,]),'$end':([1,4,5,6,7,8,9,],[0,-5,-2,-4,-6,-1,-3,]),'TYPE':([2,],[3,]),'NAME':([2,3,],[4,5,]),'VARNAME':([4,5,],[6,8,]),'VARNUM':([4,5,],[7,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'num':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> num","S'",1,None,None,None),
  ('num -> NUM TYPE NAME VARNAME','num',4,'p_num','LexParser2.py',93),
  ('num -> NUM TYPE NAME','num',3,'p_num','LexParser2.py',94),
  ('num -> NUM TYPE NAME VARNUM','num',4,'p_num','LexParser2.py',95),
  ('num -> NUM NAME VARNAME','num',3,'p_num2','LexParser2.py',101),
  ('num -> NUM NAME','num',2,'p_num2','LexParser2.py',102),
  ('num -> NUM NAME VARNUM','num',3,'p_num2','LexParser2.py',103),
]
